### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by RodrigoTeran** [Roberto-Ruiz-Obregon-Tec/Back-End#98]
Hasta este [commit](https://github.com/Roberto-Ruiz-Obregon-Tec/Back-End/commit/561673a4bc220fbfd86b7546c4b77975060d13e0) la app no funciona ya que sale este error:

```
.../controllers/scholarships.controller.js:9
const mongoose = require('mongoose')
      ^

SyntaxError: Identifier 'mongoose' has already been declared
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/rodrigoteranhernandez/Documents/RRO/BackEnd/routes/scholarships.route.js:10:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/rodrigoteranhernandez/Documents/RRO/BackEnd/app.js:34:28)

Node.js v20.9.0
```

Para que lo chequen.

**Comment by RamonaNF** [comment]
Gracias... se duplicó al resolver los merge conflicts de becas.
Ya hice un pull request de un hotfix.
